### ISSUE TITLE
Refreshing issue

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#17]
**Describe the bug**
If refreshing on Planet Question on Desktop, it will direct users to Planet Page. If refreshing any pages in planet studio on mobile, it will direct users to Planet Page. 

**To Reproduce**
just try

**Comment by AdvaithNair** [comment]
I know that this happens due to the useEffect in the main app. I'll explain a little bit so hopefully we can solve it based on this. When you load the app up or refresh it, the redux state will always start with empty information since we removed the persister in favor of a more secure YouPlanets website. Therefore, the app automatically redirects to the planet page when it notices the state being empty, which happens on load or reload.

A potential solution may include holding off on the redirect until the useEffect request to get the user information is completed. I'm thinking of adding a variable to the redux state called initialRequest, which starts off as false, but after the request, whether or not it's successful, will set to true. Only when initialRequest is true will any redirect action take place. This may be an overkill/brute force solution, but the user experience may be improved by fixing it. There may be other better solutions but that's what I'm thinking of on the top of my head.
