### ISSUE TITLE
Cannot update files

### ISSUE THREAD

**Issue by Nancyyes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#23]
<img width="419" alt="IMG_8380" src="https://user-images.githubusercontent.com/58830422/103236591-45409a00-4913-11eb-9b0f-73f1ec63b99f.png">
Hi guys,

I have tried to upload my photo and update my email and username again, but it still pops out the error. I would appreciate it if you guys could fix it.

Thanks a lot.

Best,
Nancy

**Comment by Seraph-YCZhang** [comment]
@JalenYes I cannot reproduce this

**Comment by JalenYes** [comment]
![IMG_9531](https://user-images.githubusercontent.com/40333215/103246333-1afdd500-4931-11eb-85a1-e46eff536c16.jpeg)

**Comment by AdvaithNair** [comment]
I think the culprit here is the photo. There's a good chance there is a very high res photo being used as the upload. We may want to either attempt downscaling the photo on the frontend that way the request size is reduced, or we could reject anything above a reasonable resolution (that still complies with the request size parameters). We should make sure this is the photo's fault by testing it with and without the high res photo. I've personally never seen this problem but I've also never tested against higher res photos. If the photo is the issue, other places where we attach files may be affected by this exact problem too.

**Comment by JalenYes** [comment]
> I think the culprit here is the photo. There's a good chance there is a very high res photo being used as the upload. We may want to either attempt downscaling the photo on the frontend that way the request size is reduced, or we could reject anything above a reasonable resolution (that still complies with the request size parameters). We should make sure this is the photo's fault by testing it with and without the high res photo. I've personally never seen this problem but I've also never tested against higher res photos. If the photo is the issue, other places where we attach files may be affected by this exact problem too.

Thank you! You nailed the point. Yuchen already identified the reason but didn't figure out a good solution to solve it. I think now he has a better idea about it.

**Comment by JalenYes** [comment]
wanna follow up with this issue. what is our solution now?
