### ISSUE TITLE
Unlock Content Feature not really hiding anything

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#63]
I can read everything in that post! Except for the parts under the "Join Now" button, but if you zoom in and out of the browser, the button shift, and you basically can read 100% of the content.

![image](https://user-images.githubusercontent.com/77167655/104504040-7f629a80-55a7-11eb-8fde-0b84979709da.png)

**Comment by JalenYes** [comment]
This is actually intentional. The reason is that the Unlock Content cover only shows up if the channel is public, which would be the general channel. So, I intentionally make it visible to general visitors. They can view it with a bad experience, which would trigger the sense to pay for a better experience.  This is a public channel to non-member view. 

For a private channel to non-member view, please check the image below. 
![image](https://user-images.githubusercontent.com/40333215/104509167-46322680-55b7-11eb-9559-87f7e5488b47.png)

**Comment by hansontranhai** [comment]
Ah ok, that makes a lot more sense now. I agree! Thanks for clarifying!

**Comment by JalenYes** [comment]
> Ah ok, that makes a lot more sense now. I agree! Thanks for clarifying!

Thank YOU for bringing it up! : D
